--
title: "Automating rmakrdown html output"
author: "Adam P Cribbs"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
abstract: >
  siteymlgen makes it easy to organise R Markdown website output. 
  The init() function placed within the first code chunk of the index.Rmd
  file of an R project directory will initiate the generation of an automatically 
  written _site.yml file. siteymlgen recomends a specific naming
  convention for your markdown files. This naming will ensure that
  your navbar layout is ordered according to a heirarchy.  
  siteymlgen package version: `r packageVersion("siteymlgen")`
output:
  rmarkdown::html_document:
    highlight: pygments
    toc: true
    fig_width: 5
vignette: >
  %\VignetteIndexEntry{Automating rmakrdown html output}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---

```{r pandoc_check, echo=FALSE}
if (!rmarkdown::pandoc_available()) {
  cat("pandoc is required to use ymlthis. Please visit https://pandoc.org/ for more information.")
  knitr::knit_exit()
}
```


**sitegenyml** is a package to automate the generation of _site.yml file for building Rmarkdown websites. It 

# Writing _site.yml with **sitegenyml**

**sitegenyml** automates the process of generating a _site.yml file when using Rmarkdwn to generate a website. 

Generating 

